runtime: nodejs8
env: standard
service: frontend

env_variables:
   API_KEY: ${API_KEY}

manual_scaling:
   instances: 1

handlers:
- url: /(.*\.(gif|png|jpeg|jpg|css|js|ico|woff|woff2))$
  static_files: dist/\1
  upload: dist/(.*)
- url: /(.*)
  static_files: dist/index.html
  upload: dist/index.html
